/*
============================================
; Title: api.single.service.ts (Week 5)
; Author: Professor Krasso
; Modified By: Aaron Wilson
; Date: 20 October 2019
; Description: MEAN NodeQuiz Service.
;===========================================
*/

import { Injectable, Input } from '@angular/core';
import { Observable } from 'rxjs';
import { ActivatedRoute } from '@angular/router';
import { HttpClient } from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})

export class ApiSingleService {
  private apiEndPoint;

  constructor(private route: ActivatedRoute, private http: HttpClient) { }

  // tslint:disable-next-line: ban-types
  get() {

    // Generated by typescript 1.8.10
    const route = this.route;

    route.paramMap.subscribe(params => {
      this.apiEndPoint = params.get('id');
    });

    const apiInvalidURL = 'Invalid route';
    const apiQuizURL = `http://localhost:3000/api/quizzes/${this.apiEndPoint}`;
    const apiSlideshowURL = `http://localhost:3000/api/slideshow/${this.apiEndPoint}`;

    switch (apiInvalidURL || apiQuizURL || apiSlideshowURL) {
      case apiQuizURL: {
          console.log(apiQuizURL);
          return this.http.get(apiQuizURL);
          break;
      }
      case apiSlideshowURL: {
          console.log(apiSlideshowURL);
          return this.http.get(apiSlideshowURL);
          break;
      }
      default: {
          return console.log(apiInvalidURL);
          break;
      }
    }
  }
}
